git:
  pagers:
    - pager: 'delta --diff-highlight --paging=never'
disableStartupPopups: true
gui:
  scrollHeight: 20
  mouseEvents: false #disable donate and ask question text
  showCommandLog: false
